spring:
    profiles: Dev
Message: Dev
kafka.broker: localhost:9092,localhost:9093,localhost:9094
enable.auto.commit: false
auto.commit.interval.ms:  100
group.id: group1
kafka.auto.offset.reset: earliest
kafka.topic: sec-topic

---
spring:
    profiles: Test
Message: Test